# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-29 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('state', models.CharField(max_length=255, verbose_name='Состояние')),
            ],
        ),
    ]
