# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-29 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.BooleanField(choices=[(False, 'False'), (True, 'True')], max_length=255, verbose_name='Состояние'),
        ),
    ]
