# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-29 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20170530_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройства'},
        ),
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.CharField(choices=[('Выкл', 'Выкл'), ('Вкл', 'Вкл')], default='Выкл', max_length=255, verbose_name='Состояние'),
        ),
    ]
