# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-29 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.IntegerField(verbose_name='Работа за сегодня')),
                ('month', models.IntegerField(verbose_name='Работа за месяц')),
                ('quart', models.IntegerField(verbose_name='Работа за квартал')),
                ('half_year', models.IntegerField(verbose_name='Работа за полгода')),
                ('year', models.IntegerField(verbose_name='Работа за год')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
            ],
        ),
    ]
